version: '3.8'

services:
  # 1. Official Widget (Port 3005)
  official_ui:
    container_name: edu_official_ui
    build:
      context: ../official_ui
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    volumes:
      - ../official_ui:/app
      - /app/node_modules
    env_file:
      - ../.env
    environment:
      - PORT=3005 # <--- ADD THIS to force React to run on internal port 3005
      - REACT_APP_API_URL=http://localhost:8807
      - VITE_FILE_UPLOAD_URL=http://localhost:8008
      - CHOKIDAR_USEPOLLING=true
    networks:
      - edu_app_bridge

  # 2. Custom Dashboard (Port 5180)
  frontend:
    container_name: edu_frontend
    build: ../frontend
    ports:
      - "5180:5180" 
    volumes:
      - ../frontend:/app       
      - /app/node_modules     
    env_file:
      - ../.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:8809
      - VITE_PORT=5180 # Forces Vite to listen on internal port 5180 instead of default 5173
    networks:
      - edu_app_bridge

networks:
  edu_app_bridge:
    external: true